services:
  - type: web
    name: judge0-api
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: REDIS_HOST
        value: redis://red-d20a1lqli9vc739r84bg:6379
      - key: REDIS_PASSWORD
        sync: false
      - key: POSTGRES_HOST
        value: postgresql://judge0postgres_user:fxZAeqpyTA3I5Cpfc6BBHMZCydfSDrNQ@dpg-d20a0d6mcj7s73atl5fg-a/judge0postgres:5432
      - key: POSTGRES_DB
        value: judge0postgres
      - key: POSTGRES_USER
        value: judge0postgres_user
      - key: POSTGRES_PASSWORD
        value: fxZAeqpyTA3I5Cpfc6BBHMZCydfSDrNQ
      - key: ENABLE_AUTH_HEADERS
        value: false
    ports:
      - 2358
